openkm/document-management-system

src/main/java/com/openkm/util/PathUtils.java

https://jira.openkm.com/browse/OCM-30

V6.3/ocm 30 Error while creating folder with character '

---

src/main/java/com/openkm/core/Config.java
src/main/java/com/openkm/servlet/RepositoryStartupServlet.java
src/main/java/com/openkm/util/CronTabUtils.java

https://github.com/openkm/document-management-system/issues/30

version6.3/OCM-30-Remove noreply@openkm.com from crontab

---

src/main/java/com/openkm/bean/Mail.java
src/main/java/com/openkm/dao/HibernateUtil.java
src/main/java/com/openkm/dao/bean/MailAccount.java
src/main/java/com/openkm/dao/bean/MailImportError.java
src/main/java/com/openkm/util/MailUtils.java
src/main/resources/com/openkm/dao/bean/MailAccount.hbm.xml

https://jira.openkm.com/browse/OCM-29

V6.3/OCM-29-Solve problems reading non UTF-8 mails

---

src/main/java/com/openkm/servlet/DownloadServlet.java
src/main/java/com/openkm/servlet/ImageLogoServlet.java
src/main/java/com/openkm/servlet/admin/DbRepositoryViewServlet.java
src/main/java/com/openkm/servlet/admin/LogCatServlet.java
src/main/java/com/openkm/servlet/frontend/DownloadServlet.java
src/main/java/com/openkm/servlet/frontend/ExecuteReportServlet.java
src/main/java/com/openkm/util/WebUtils.java

InpustStream -> is.available() is limited to 2GB not allowing file >2GB to download properly
https://github.com/openkm/document-management-system/issues/40
Test was done and now download correctly

issues/40-InpustStream -> is.available() is limited to 2GB not allowing file

---

src/main/java/com/openkm/bean/QueryResult.java
src/main/java/com/openkm/module/SearchModule.java
src/main/java/com/openkm/module/db/DbSearchModule.java
src/main/java/com/openkm/module/db/base/BaseDocumentModule.java
src/main/java/com/openkm/util/CSVUtil.java
src/main/java/com/openkm/util/GWTUtil.java

Ahora funciona las busquedas correctamente en la aplicacion Android con estos cambios realizados se realizo las pruebas necesarias.
Fix #52

#52 Add missing search method for compatibility

---

src/main/java/com/openkm/module/db/DbDocumentModule.java
src/main/java/com/openkm/module/db/DbPropertyGroupModule.java
src/main/java/com/openkm/servlet/frontend/DocumentServlet.java
src/main/webapp/login_desktop.jsp
src/main/webapp/login_mobile.jsp

Automation to capture move of node TO new folder path

---

src/main/java/com/openkm/module/db/DbPropertyGroupModule.java

Error while updating metadata

---

pom.xml
src/main/java/com/openkm/servlet/RepositoryStartupServlet.java

Remove log4j dependencies

---

src/main/java/com/openkm/jaas/PrincipalUtils.java
src/main/java/com/openkm/servlet/PasswordResetServlet.java
src/main/webapp/password_reset.jsp

Resolved reset password.
Update interface reset_passoword.jsp
Fix #73

Forgot your Password Error

---

src/main/java/com/openkm/api/OKMSearch.java
src/main/java/com/openkm/module/SearchModule.java
src/main/java/com/openkm/module/db/DbSearchModule.java

Add support for Lucene plain queries

---

src/main/java/com/openkm/frontend/client/widget/toolbar/ToolBar.java

Massive add category not working in 6.3.6-87d181f release

---

src/main/java/com/openkm/frontend/client/widget/filebrowser/FileBrowser.java

Filter nodes not working in Catergory view not working 
Fixes #71

Filter nodes not working in Category view

---

src/main/java/com/openkm/frontend/client/util/validator/ExtendedDefaultValidatorProcessor.java
src/main/java/com/openkm/frontend/client/util/validator/ValidatorPluginToFire.java
src/main/java/com/openkm/frontend/client/util/validator/ValidatorToFire.java
src/main/java/com/openkm/frontend/client/widget/ReportPopup.java
src/main/java/com/openkm/frontend/client/widget/dashboard/workflow/WorkflowFormPanel.java
src/main/java/com/openkm/frontend/client/widget/filebrowser/ExtendedScrollTable.java
src/main/java/com/openkm/frontend/client/widget/filebrowser/FileBrowser.java
src/main/java/com/openkm/frontend/client/widget/filebrowser/FileBrowserController.java
src/main/java/com/openkm/frontend/client/widget/foldertree/FolderTree.java
src/main/java/com/openkm/frontend/client/widget/form/FormManager.java
src/main/java/com/openkm/frontend/client/widget/massive/PropertyGroupPopup.java
src/main/java/com/openkm/frontend/client/widget/massive/UpdatePropertyGroupPopup.java
src/main/java/com/openkm/frontend/client/widget/properties/PropertyGroup.java
src/main/java/com/openkm/frontend/client/widget/properties/TabDocument.java
src/main/java/com/openkm/frontend/client/widget/properties/TabFolder.java
src/main/java/com/openkm/frontend/client/widget/properties/TabMail.java
src/main/java/com/openkm/frontend/client/widget/propertygroup/PropertyGroupWidget.java
src/main/java/com/openkm/frontend/client/widget/searchin/SearchMetadata.java
src/main/java/com/openkm/frontend/client/widget/searchresult/ExtendedScrollTable.java
src/main/java/com/openkm/frontend/client/widget/searchresult/SearchFullResult.java
src/main/java/com/openkm/frontend/client/widget/upload/FancyFileUpload.java
src/main/java/com/openkm/frontend/client/widget/upload/FileUploadPopup.java
src/main/java/com/openkm/frontend/client/widget/wizard/TemplateWizardPopup.java
src/main/java/com/openkm/frontend/client/widget/wizard/WizardPopup.java
src/main/java/com/openkm/frontend/client/widget/wizard/WorkflowWidget.java

Autoscript renaming throws error message "Document path not found"

---

src/main/java/com/openkm/core/Config.java

max.search.clauses paramter is not accessible in community edition
Fix #84

max.search.clauses paramter is not accessible in community edition

---

pom.xml
src/main/java/com/openkm/core/Swagger2Config.java
src/main/java/com/openkm/rest/endpoint/AuthService.java
src/main/java/com/openkm/rest/endpoint/DocumentService.java
src/main/java/com/openkm/rest/endpoint/FolderService.java
src/main/java/com/openkm/rest/endpoint/MailService.java
src/main/java/com/openkm/rest/endpoint/NoteService.java
src/main/java/com/openkm/rest/endpoint/PropertyGroupService.java
src/main/java/com/openkm/rest/endpoint/PropertyService.java
src/main/java/com/openkm/rest/endpoint/RepositoryService.java
src/main/java/com/openkm/rest/endpoint/SearchService.java
src/main/java/com/openkm/rest/endpoint/TestService.java
src/main/webapp/WEB-INF/appContext.xml
src/main/webapp/WEB-INF/rest.xml

Add swagger support

---

src/main/java/com/openkm/servlet/admin/StatsGraphServlet.java
src/main/webapp/admin/stats.jsp

Design improvements in administration Statistics section enhancement

---

src/main/java/com/openkm/servlet/admin/MimeTypeServlet.java
src/main/webapp/admin/config_edit.jsp
src/main/webapp/admin/mime_edit.jsp
src/main/webapp/admin/mime_list.jsp
src/main/webapp/js/utils.js

Design improvements in administration Mime types section enhancement

---

src/main/webapp/admin/crontab_edit.jsp
src/main/webapp/admin/crontab_list.jsp

Design improvements in administration Crontab section enhancement

---

src/main/webapp/admin/generate_thesaurus.jsp

Design improvements in administration Thesaurus section enhancement

---

src/main/webapp/admin/profile_edit.jsp
src/main/webapp/admin/profile_filebrowser.jsp
src/main/webapp/admin/profile_list.jsp
src/main/webapp/admin/profile_misc.jsp
src/main/webapp/admin/profile_tab.jsp
src/main/webapp/admin/profile_wizard.jsp

Design improvements in administration Profiles section enhancement

---

src/main/webapp/admin/repository_export.jsp

Design improvements in administration Export section enhancement

---

src/main/java/com/openkm/servlet/admin/LanguageServlet.java
src/main/webapp/admin/language_edit.jsp
src/main/webapp/admin/language_list.jsp
src/main/webapp/admin/translation_add.jsp
src/main/webapp/admin/translation_edit.jsp

Design improvements in administration Language section enhancement

---

src/main/webapp/admin/report_edit.jsp
src/main/webapp/admin/report_get_params.jsp
src/main/webapp/admin/report_list.jsp
src/main/webapp/admin/report_param_list.jsp

Design improvements in administration Reports section enhancement

---

src/main/webapp/admin/process_definition_list.jsp
src/main/webapp/admin/process_definition_view.jsp
src/main/webapp/admin/process_instance_view.jsp
src/main/webapp/admin/task_instance_view.jsp
src/main/webapp/admin/token_view.jsp

Design improvements in administration Workflow section enhancement

---

src/main/java/com/openkm/servlet/admin/ScriptingServlet.java
src/main/webapp/admin/menu.jsp
src/main/webapp/admin/scripting.jsp

Design improvements in administration Scripting section enhancement

---

src/main/webapp/admin/database_query.jsp

Design improvements in administration Database Query section enhancement

---

src/main/java/com/openkm/servlet/admin/OmrServlet.java
src/main/webapp/admin/omr_check.jsp
src/main/webapp/admin/omr_edit.jsp
src/main/webapp/admin/omr_edit_asc.jsp
src/main/webapp/admin/omr_edit_fields.jsp
src/main/webapp/admin/omr_list.jsp

Design improvements in administration OMR section enhancement

---

src/main/webapp/admin/activity_log.jsp

Minor UI defect, not able to empty value list in Activity Log Section

---

src/main/java/com/openkm/util/impexp/RepositoryImporter.java
src/main/webapp/admin/repository_import.jsp

Design improvements in administration Import section enhancement

---

src/main/webapp/admin/scripting.jsp

Reduce the space between buttons in the scripting view

---

src/main/java/com/openkm/bean/AppVersion.java

OpenKM-6.3.6.zip Why this one is Professional Extension

---

src/main/webapp/admin/repository_export.jsp
src/main/webapp/admin/repository_import.jsp

Minor defect in export and import features

---

src/main/java/com/openkm/principal/OpenLdapPrincipalAdapter.java

LDAP integration: add support for operational attributes, by retrieving attributes by name.

---

javadoc.sh
pom.xml

Error generating javadoc with JDK 1.8

---

src/main/java/com/openkm/frontend/client/widget/searchin/ControlSearchIn.java
src/main/java/com/openkm/servlet/frontend/CSVExporterServlet.java

CSV Exporter doesn't work

---

src/main/java/com/openkm/extension/frontend/client/widget/wiki/finddocument/FindDocumentSelectPopup.java
src/main/resources/i18n/en-GB.sql

Popup UI defect in wiki view

---

src/main/java/com/openkm/frontend/client/panel/ExtendedDockPanel.java
src/main/java/com/openkm/frontend/client/util/WorkspaceUserProperties.java

Document can be download when disable download on user profile

---

src/main/java/com/openkm/core/Config.java
src/main/webapp/admin/repository_export.jsp

Prevent to export into $TOMCAT_HOME/webapps

---

src/main/java/com/openkm/automation/AutomationUtils.java
src/main/java/com/openkm/dao/AutomationDAO.java
src/main/java/com/openkm/dao/bean/AutomationRule.java
src/main/java/com/openkm/module/db/DbAuthModule.java
src/main/java/com/openkm/spring/LoggerListener.java

Add login and logout automation events

---

pom.xml

Adding profiles to create jar client and dependencies

---

check-maven-conflicts.sh
pom.xml

check maven dependency conflicts

---

src/main/webapp/login_desktop.jsp
src/main/webapp/login_mobile.jsp

Logo is not changing in the home page

---

src/main/java/com/openkm/frontend/client/widget/wizard/WorkflowWidget.java

Repeated Workflow instance with run config
fix #191

Repeated Workflow instance with run config

---

src/main/java/com/openkm/util/StackTraceUtils.java

Add isCallingMe in the StackTraceUtils class

---

src/main/java/com/openkm/extension/servlet/DataBrowserServlet.java
src/main/java/com/openkm/servlet/admin/RepositoryServlet.java
src/main/webapp/admin/menu.jsp
src/main/webapp/admin/repository_export.jsp
src/main/webapp/admin/repository_import.jsp
src/main/webapp/extension/data_browser.jsp

java.lang.NullPointerException when bulk uploading documents

---

pom.xml
src/main/java/com/openkm/util/ReportUtils.java

Random problems when starting OpenKM

---

pom.xml
src/main/java/com/openkm/extractor/PdfTextExtractor.java

Huge amount of tmp-files in tomcat/temp

---

src/main/java/com/openkm/servlet/admin/RebuildIndexesServlet.java

More detailed error information in the log of lucene indexes

---

src/main/java/com/openkm/extension/servlet/DataBrowserServlet.java
src/main/webapp/extension/data_browser.jsp

Error al seleccionar un path con acentos desde el automation

---

src/main/java/com/openkm/rest/endpoint/FolderService.java

Add createMissingFolders

---

src/main/java/com/openkm/rest/endpoint/AuthService.java
src/main/java/com/openkm/rest/util/ChangeSecurity.java
src/main/java/com/openkm/rest/util/RevokedRole.java
src/main/java/com/openkm/rest/util/RevokedRoleList.java
src/main/java/com/openkm/rest/util/RevokedUser.java
src/main/java/com/openkm/rest/util/RevokedUserList.java

Extend AuthService API

---

src/main/java/com/openkm/bean/ContentInfo.java
src/main/java/com/openkm/dao/NodeDocumentDAO.java
src/main/java/com/openkm/dao/NodeFolderDAO.java
src/main/java/com/openkm/dao/NodeMailDAO.java
src/main/java/com/openkm/dao/SearchDAO.java
src/main/java/com/openkm/module/db/base/BaseFolderModule.java
src/main/java/com/openkm/rest/endpoint/FolderService.java

Extend FolderService API

---

src/main/java/com/openkm/dao/NodeMailDAO.java
src/main/java/com/openkm/dao/SearchDAO.java
src/main/java/com/openkm/rest/endpoint/SearchService.java

Extend SearchService API

---

src/main/java/com/openkm/rest/endpoint/PropertyGroupService.java
src/main/java/com/openkm/rest/util/SuggestionList.java

Extend PropertyGroupService API

---

src/main/java/com/openkm/rest/endpoint/RepositoryService.java
src/main/java/com/openkm/rest/util/HqlQueryResultColumns.java

Extend RepositoryService API

---

src/main/java/com/openkm/frontend/client/widget/searchin/SearchControl.java
src/main/java/com/openkm/frontend/client/widget/searchin/SearchIn.java
src/main/java/com/openkm/frontend/client/widget/searchin/SearchNormal.java

Advanced search folder shows only trash

---

src/main/java/com/openkm/rest/endpoint/DocumentService.java

Extend DocumentService API

---

pom.xml
src/main/java/com/openkm/core/UserMailImporter.java
src/main/java/com/openkm/extractor/ExifTextExtractor.java
src/main/java/com/openkm/extractor/HTMLParser.java
src/main/java/com/openkm/extractor/MsOffice2007TextExtractor.java
src/main/java/com/openkm/extractor/OpenOfficeTextExtractor.java
src/main/java/com/openkm/extractor/SourceCodeTextExtractor.java
src/main/java/com/openkm/extractor/XMLTextExtractor.java
src/main/java/com/openkm/util/MailUtils.java

Extracted Text file xlsx is not working correctly

---

src/main/java/com/openkm/util/MailUtils.java

Openkm sends wrong Content-Length header for email attachments

---

pom.xml
src/main/java/com/openkm/core/Config.java
src/main/java/com/openkm/servlet/RepositoryStartupServlet.java
src/main/java/com/openkm/servlet/admin/ConfigServlet.java
src/main/java/com/openkm/util/CustomToStringStyle.java
src/main/java/com/openkm/util/DocConverter.java
src/main/java/com/openkm/util/EnvironmentDetector.java

Avoid use of LibreOffice as a service due to conversion problems

---

pom.xml
src/main/java/com/openkm/api/OKMMail.java
src/main/java/com/openkm/module/db/DbMailModule.java
src/main/java/com/openkm/module/db/base/BaseMailModule.java
src/main/java/com/openkm/rest/endpoint/MailService.java
src/main/java/com/openkm/ws/endpoint/AuthService.java
src/main/java/com/openkm/ws/endpoint/BookmarkService.java
src/main/java/com/openkm/ws/endpoint/DashboardService.java
src/main/java/com/openkm/ws/endpoint/DocumentService.java
src/main/java/com/openkm/ws/endpoint/FolderService.java
src/main/java/com/openkm/ws/endpoint/MailService.java
src/main/java/com/openkm/ws/endpoint/NoteService.java
src/main/java/com/openkm/ws/endpoint/NotificationService.java
src/main/java/com/openkm/ws/endpoint/PropertyGroupService.java
src/main/java/com/openkm/ws/endpoint/PropertyService.java
src/main/java/com/openkm/ws/endpoint/RepositoryService.java
src/main/java/com/openkm/ws/endpoint/SearchService.java
src/main/java/com/openkm/ws/endpoint/WorkflowService.java

Extend MailService API

---

src/main/java/com/openkm/dao/bean/Bookmark.java
src/main/java/com/openkm/module/BookmarkModule.java
src/main/java/com/openkm/module/db/DbBookmarkModule.java
src/main/java/com/openkm/rest/endpoint/BookmarkService.java
src/main/java/com/openkm/rest/util/BookmarkList.java
src/main/webapp/WEB-INF/rest.xml

Extend BookmarkService API

---

src/main/java/com/openkm/bean/workflow/Comment.java
src/main/java/com/openkm/bean/workflow/ProcessDefinition.java
src/main/java/com/openkm/bean/workflow/ProcessInstance.java
src/main/java/com/openkm/bean/workflow/TaskInstance.java
src/main/java/com/openkm/bean/workflow/Token.java
src/main/java/com/openkm/bean/workflow/Transition.java
src/main/java/com/openkm/rest/endpoint/PropertyGroupService.java
src/main/java/com/openkm/rest/endpoint/WorkflowService.java
src/main/java/com/openkm/rest/util/ProcessDefinitionForm.java
src/main/java/com/openkm/rest/util/ProcessDefinitionFormsList.java
src/main/java/com/openkm/rest/util/ProcessDefinitionList.java
src/main/java/com/openkm/rest/util/ProcessInstanceList.java
src/main/java/com/openkm/rest/util/TaskInstanceList.java
src/main/java/com/openkm/ws/common/util/FormElementComplex.java
src/main/java/com/openkm/ws/endpoint/PropertyGroupService.java
src/main/java/com/openkm/ws/endpoint/WorkflowService.java
src/main/webapp/WEB-INF/rest.xml

Extend WorkflowService API

---

src/main/java/com/openkm/frontend/client/widget/wizard/WizardPopup.java

Multiple Automation actions not running

---

src/main/java/com/openkm/servlet/HtmlPreviewServlet.java
src/main/java/com/openkm/servlet/admin/BaseServlet.java
src/main/webapp/WEB-INF/tlds/utils.tld
src/main/webapp/error.jsp

Cross Site Scrtipting issue

---

src/main/java/com/openkm/api/OKMDocument.java
src/main/java/com/openkm/api/OKMNotification.java
src/main/java/com/openkm/cmis/CmisRepository.java
src/main/java/com/openkm/extension/servlet/StaplingDownloadServlet.java
src/main/java/com/openkm/extension/servlet/ZohoServlet.java
src/main/java/com/openkm/module/DocumentModule.java
src/main/java/com/openkm/module/NotificationModule.java
src/main/java/com/openkm/module/common/CommonNotificationModule.java
src/main/java/com/openkm/module/db/DbDocumentModule.java
src/main/java/com/openkm/module/db/DbNotificationModule.java
src/main/java/com/openkm/module/db/base/BaseDocumentModule.java
src/main/java/com/openkm/servlet/HtmlPreviewServlet.java
src/main/java/com/openkm/servlet/SyntaxHighlighterServlet.java
src/main/java/com/openkm/servlet/TextToSpeechServlet.java
src/main/java/com/openkm/servlet/admin/CheckTextExtractionServlet.java
src/main/java/com/openkm/servlet/frontend/DocumentServlet.java
src/main/java/com/openkm/servlet/frontend/DownloadServlet.java
src/main/java/com/openkm/servlet/frontend/MailServlet.java
src/main/java/com/openkm/servlet/frontend/MassiveServlet.java
src/main/java/com/openkm/servlet/frontend/NotifyServlet.java
src/main/java/com/openkm/test/api/DocumentTest.java
src/main/java/com/openkm/util/MailUtils.java
src/main/java/com/openkm/util/backup/RepositoryS3Backup.java
src/main/java/com/openkm/util/impexp/RepositoryExporter.java
src/main/java/com/openkm/webdav/resource/DocumentResource.java
src/main/java/com/openkm/webdav/resource/MailResource.java
src/main/java/com/openkm/ws/endpoint/DocumentService.java
src/main/java/com/openkm/ws/endpoint/NotificationService.java

The method getContent from DbDocumentModule seems not implementing the checkout

---

src/main/java/com/openkm/servlet/admin/ConfigServlet.java

Program Config

---

src/main/java/com/openkm/util/MailUtils.java

Mail mark seen option set all old seen mails as unseen

---

src/main/java/com/openkm/extractor/OpenOfficeTextExtractor.java
src/main/java/com/openkm/extractor/XMLTextExtractor.java

XXE injection security vulnerability

---

pom.xml
src/main/java/com/openkm/rest/endpoint/NotificationService.java
src/main/webapp/WEB-INF/rest.xml

Extend NotificationService API

---

src/main/java/com/openkm/api/OKMDocument.java
src/main/java/com/openkm/module/db/base/BaseDocumentModule.java
src/main/java/com/openkm/rest/endpoint/DocumentService.java
src/main/java/com/openkm/util/FormUtils.java
src/main/java/com/openkm/util/ImageUtils.java
src/main/java/com/openkm/util/PDFUtils.java

Document managing plugin and API

---

src/main/java/com/openkm/frontend/client/widget/form/FormManager.java

Use 'separator' metadata element without 'label' attribute

---

pom.xml
publish.sh
src/main/java/com/openkm/frontend/client/widget/properties/SyntaxHighlighterPreview.java
src/main/java/com/openkm/servlet/SyntaxHighlighterServlet.java

Cannot preview document with Thai Filename

---

src/main/java/com/openkm/frontend/client/util/Util.java
src/main/java/com/openkm/frontend/client/widget/filebrowser/uploader/DragAndDropUploadFilesPopup.java
src/main/java/com/openkm/util/WebUtils.java

Problems with special characters (at least ampersands) in filenames

---

src/main/java/com/openkm/core/Config.java
src/main/java/com/openkm/extractor/RegisteredExtractors.java

I think parameter registered.text.extractors should be removed

---

src/main/java/com/openkm/util/SecureStore.java

Remove DES from SecureStore

---

src/main/java/com/openkm/frontend/client/bean/GWTWorkspace.java
src/main/java/com/openkm/servlet/frontend/WorkspaceServlet.java

Wrong major minor increment version in the UI

---

src/main/java/com/openkm/rest/endpoint/DashboardService.java
src/main/java/com/openkm/rest/util/DashboardDocumentResultList.java
src/main/java/com/openkm/rest/util/DashboardFolderResultList.java
src/main/java/com/openkm/rest/util/DashboardMailResultList.java
src/main/webapp/WEB-INF/rest.xml

Extend DashboardService API

---

pom.xml
src/main/java/com/openkm/extractor/OOTextExtractor.java
src/main/java/com/openkm/frontend/client/util/Util.java
src/main/java/com/openkm/frontend/client/widget/properties/Preview.java
src/main/java/com/openkm/frontend/client/widget/properties/TabDocument.java
src/main/java/com/openkm/util/DocConverter.java

Problem with document preview

---

src/main/java/com/openkm/cmis/CmisRepository.java

CmisRepository version label wrongly returns filename instead of actualVersion

---

src/main/java/com/openkm/util/FormatUtil.java

Reported XSS vulnerability

---

src/main/java/com/openkm/module/db/DbNoteModule.java
src/main/java/com/openkm/util/FormatUtil.java

XSS vulnerability

---

src/main/java/com/openkm/servlet/SyntaxHighlighterServlet.java

XSS vulnerability in preview
